<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-24 at 03:36:12.
 */
class MathInputCheckTest extends MediaWikiTestCase
{
    /**
     * @var MathInputCheck
     */
    protected $object;


//    /**
//     * @covers MathInputCheck::isSecure
//     * @todo   Implement testIsSecure().
//     */
//    public function testIsSecure()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MathInputCheck::getError
//     * @todo   Implement testGetError().
//     */
//    public function testGetError()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MathInputCheck::getSecureTex
//     * @todo   Implement testGetSecureTex().
//     */
//    public function testGetSecureTex()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
}
