<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-24 at 03:36:12.
 */
class MathInputCheckTest extends MediaWikiTestCase
{
<<<<<<< HEAD   (4bb5ca Style: Apply stylize.php)
    /**
     * @var MathInputCheck
     */
    protected $object;


//    /**
//     * @covers MathInputCheck::isSecure
//     * @todo   Implement testIsSecure().
//     */
//    public function testIsSecure()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MathInputCheck::getError
//     * @todo   Implement testGetError().
//     */
//    public function testGetError()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
//
//    /**
//     * @covers MathInputCheck::getSecureTex
//     * @todo   Implement testGetSecureTex().
//     */
//    public function testGetSecureTex()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//          'This test has not been implemented yet.'
//        );
//    }
=======
	/**
	 * @covers MathInputCheck::isValid
	 */
	public function testIsValid() {
		$InputCheck = $this->getMockBuilder( 'MathInputCheck' )->getMock();
		$this->assertEquals( $InputCheck->IsValid() , false );
	}

	/**
	 * @covers MathInputCheck::getError
	 * @todo   Implement testGetError().
	 */
	public function testGetError() {
		$InputCheck = $this->getMockBuilder( 'MathInputCheck' )->getMock();
		$this->assertNull( $InputCheck->getError() );
	}

	/**
	 * @covers MathInputCheck::getValidTex
	 */
	public function testGetValidTex() {
		$InputCheck = $this->getMockBuilder( 'MathInputCheck' )
			->setConstructorArgs(array('some tex input'))
			->getMock();
		$this->assertNull( $InputCheck->getValidTex() );
	}
>>>>>>> BRANCH (6a0af8 Validate TeX input for all renderers, not just texvc)
}
