<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-24 at 03:46:07.
 */
class MathInputCheckTexvcTest extends MediaWikiTestCase {

	/**
	 * @var MathInputCheckTexvc
	 */
	protected $BadObject;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		parent::setUp();
		$this->BadObject = new MathInputCheckTexvc('\newcommand{\text{do evil things}}');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

//	/**
//	 * @covers MathInputCheckTexvc::convertTexvcError
//	 * @todo   Implement testConvertTexvcError().
//	 */
//	public function testConvertTexvcError() {
//		// Remove the following lines when you implement this test.
//		$this->markTestIncomplete(
//				'This test has not been implemented yet.'
//		);
//	}

	/**
	 * @covers MathInputCheckTexvc::isSecure
	 * @todo   Implement testIsSecure().
	 */
	public function testIsSecure() {
		$this->assertFalse($this->BadObject->isSecure());
		// Remove the following lines when you implement this test.
	}

}
