(* vim: set sw=8 ts=8 et: *)
open Parser
open Tex
open Util


let tex_part = function
    HTMLABLE (_,t,_) -> t
  | HTMLABLEM (_,t,_) -> t
  | HTMLABLEC (_,t,_) -> t
  | MHTMLABLEC (_,t,_,_,_) -> t
  | HTMLABLE_BIG (t,_) -> t
  | TEX_ONLY t -> t

let rec render_tex = function
    TEX_FQ (a,b,c) -> (render_tex a) ^ "_{" ^ (render_tex  b) ^ "}^{" ^ (render_tex  c) ^ "}"
  | TEX_DQ (a,b) -> (render_tex a) ^ "_{" ^ (render_tex  b) ^ "}"
  | TEX_UQ (a,b) -> (render_tex a) ^ "^{" ^ (render_tex  b) ^ "}"
  | TEX_FQN (a,b) -> "_{" ^ (render_tex  a) ^ "}^{" ^ (render_tex  b) ^ "}"
  | TEX_DQN (a) -> "_{" ^ (render_tex  a) ^ "}"
  | TEX_UQN (a) -> "^{" ^ (render_tex  a) ^ "}"
  | TEX_LITERAL s -> tex_part s
  | TEX_FUN1 (f,a) -> "{" ^ f ^ " " ^ (render_tex a) ^ "}"
  | TEX_FUN1nb (f,a) -> f ^ " " ^ (render_tex a)
  | TEX_FUN1hl (f,_,a) -> "{" ^ f ^ " " ^ (render_tex a) ^ "}"
  | TEX_FUN1hf (f,_,a) -> "{" ^ f ^ " " ^ (render_tex a) ^ "}"
  | TEX_DECLh (f,_,a) -> "{" ^ f ^ "{" ^ (mapjoin render_tex a) ^ "}}"
  | TEX_FUN2 (f,a,b) -> "{" ^ f ^ " " ^ (render_tex a) ^ (render_tex b) ^ "}"
  | TEX_FUN2nb (f,a,b) -> f ^ (render_tex a) ^ (render_tex b)
  | TEX_FUN2h (f,_,a,b) -> "{" ^ f ^ " " ^ (render_tex a) ^ (render_tex b) ^ "}"
  | TEX_FUN2sq (f,a,b) -> "{" ^ f ^ "[ " ^ (render_tex a) ^ "]" ^ (render_tex b) ^ "}"
  | TEX_CURLY (tl) -> "{" ^ (mapjoin render_tex tl) ^ "}"
  | TEX_INFIX (s,ll,rl) -> "{" ^ (mapjoin render_tex ll) ^ " " ^ s ^ "" ^ (mapjoin render_tex rl) ^ "}"
  | TEX_INFIXh (s,_,ll,rl) -> "{" ^ (mapjoin render_tex ll) ^ " " ^ s ^ "" ^ (mapjoin render_tex rl) ^ "}"
  | TEX_BOX (bt,s) -> "{"^bt^"{" ^ s ^ "}}"
  | TEX_BIG (bt,d) -> "{"^bt^(tex_part d)^"}"
  | TEX_MATRIX (t,rows) -> "{\\begin{"^t^"}"^(mapjoine "\\\\" (mapjoine "&" (mapjoin render_tex)) rows)^"\\end{"^t^"}}"
  | TEX_LR (l,r,tl) -> "\\left "^(tex_part l)^(mapjoin render_tex tl)^"\\right "^(tex_part r)


(* Turn that into hash table lookup *)
exception Illegal_tex_function of string

let find = function
      "\\alpha"            -> LITERAL (TEX_ONLY  "\\alpha ")
    | "\\Alpha"            -> LITERAL (TEX_ONLY    "\\mathrm{A}")
    | "\\beta"             -> LITERAL (TEX_ONLY  "\\beta ")
    | "\\Beta"             -> LITERAL (TEX_ONLY    "\\mathrm{B}")
    | "\\gamma"            -> LITERAL (TEX_ONLY  "\\gamma ")
    | "\\Gamma"            -> LITERAL (TEX_ONLY "\\Gamma ")
    | "\\delta"            -> LITERAL (TEX_ONLY  "\\delta ")
    | "\\Delta"            -> LITERAL (TEX_ONLY "\\Delta ")
    | "\\epsilon"          -> LITERAL (TEX_ONLY "\\epsilon ")
    | "\\Epsilon"          -> LITERAL (TEX_ONLY    "\\mathrm{E}")
    | "\\varepsilon"       -> LITERAL (TEX_ONLY "\\varepsilon ")
    | "\\zeta"             -> LITERAL (TEX_ONLY  "\\zeta ")
    | "\\Zeta"             -> LITERAL (TEX_ONLY    "\\mathrm{Z}")
    | "\\eta"              -> LITERAL (TEX_ONLY  "\\eta ")
    | "\\Eta"              -> LITERAL (TEX_ONLY    "\\mathrm{H}")
    | "\\theta"            -> LITERAL (TEX_ONLY  "\\theta ")
    | "\\Theta"            -> LITERAL (TEX_ONLY "\\Theta ")
    | "\\vartheta"         -> LITERAL (TEX_ONLY  "\\vartheta ")
    | "\\thetasym"         -> LITERAL (TEX_ONLY  "\\vartheta ")
    | "\\iota"             -> LITERAL (TEX_ONLY  "\\iota ")
    | "\\Iota"             -> LITERAL (TEX_ONLY    "\\mathrm{I}")
    | "\\kappa"            -> LITERAL (TEX_ONLY  "\\kappa ")
    | "\\Kappa"            -> LITERAL (TEX_ONLY    "\\mathrm{K}")
    | "\\lambda"           -> LITERAL (TEX_ONLY  "\\lambda ")
    | "\\Lambda"           -> LITERAL (TEX_ONLY "\\Lambda ")
    | "\\mu"               -> LITERAL (TEX_ONLY  "\\mu ")
    | "\\Mu"               -> LITERAL (TEX_ONLY    "\\mathrm{M}")
    | "\\nu"               -> LITERAL (TEX_ONLY  "\\nu ")
    | "\\Nu"               -> LITERAL (TEX_ONLY    "\\mathrm{N}")
    | "\\omicron"          -> LITERAL (TEX_ONLY    "\\mathrm{o}")
    | "\\Omicron"          -> LITERAL (TEX_ONLY    "\\mathrm{O}")
    | "\\pi"               -> LITERAL (TEX_ONLY  "\\pi ")
    | "\\Pi"               -> LITERAL (TEX_ONLY "\\Pi ")
    | "\\varpi"            -> LITERAL (TEX_ONLY "\\varpi ")
    | "\\rho"              -> LITERAL (TEX_ONLY  "\\rho ")
    | "\\Rho"              -> LITERAL (TEX_ONLY    "\\mathrm{P}")
    | "\\varrho"           -> LITERAL (TEX_ONLY "\\varrho ")
    | "\\sim"              -> LITERAL (TEX_ONLY  "\\sim ")
    | "\\sigma"            -> LITERAL (TEX_ONLY  "\\sigma ")
    | "\\Sigma"            -> LITERAL (TEX_ONLY "\\Sigma ")
    | "\\varsigma"         -> LITERAL (TEX_ONLY "\\varsigma ")
    | "\\tau"              -> LITERAL (TEX_ONLY  "\\tau ")
    | "\\Tau"              -> LITERAL (TEX_ONLY    "\\mathrm{T}")
    | "\\upsilon"          -> LITERAL (TEX_ONLY  "\\upsilon ")
    | "\\Upsilon"          -> LITERAL (TEX_ONLY "\\Upsilon ")
    | "\\phi"              -> LITERAL (TEX_ONLY "\\phi ")
    | "\\Phi"              -> LITERAL (TEX_ONLY "\\Phi ")
    | "\\varphi"           -> LITERAL (TEX_ONLY "\\varphi ")
    | "\\chi"              -> LITERAL (TEX_ONLY  "\\chi ")
    | "\\Chi"              -> LITERAL (TEX_ONLY    "\\mathrm{X}")
    | "\\psi"              -> LITERAL (TEX_ONLY  "\\psi ")
    | "\\Psi"              -> LITERAL (TEX_ONLY "\\Psi ")
    | "\\omega"            -> LITERAL (TEX_ONLY  "\\omega ")
    | "\\Omega"            -> LITERAL (TEX_ONLY "\\Omega ")
    | "\\xi"               -> LITERAL (TEX_ONLY  "\\xi ")
    | "\\Xi"               -> LITERAL (TEX_ONLY "\\Xi ")
    | "\\aleph"            -> LITERAL (TEX_ONLY  "\\aleph ")
    | "\\alef"             -> LITERAL (TEX_ONLY  "\\aleph ")
    | "\\alefsym"          -> LITERAL (TEX_ONLY  "\\aleph ")
    | "\\larr"             -> LITERAL (TEX_ONLY  "\\leftarrow ")
    | "\\leftarrow"        -> LITERAL (TEX_ONLY  "\\leftarrow ")
    | "\\rarr"             -> LITERAL (TEX_ONLY  "\\rightarrow ")
    | "\\to"               -> LITERAL (TEX_ONLY  "\\to ")
    | "\\gets"             -> LITERAL (TEX_ONLY  "\\gets ")
    | "\\rightarrow"       -> LITERAL (TEX_ONLY  "\\rightarrow ")
    | "\\longleftarrow"    -> LITERAL (TEX_ONLY  "\\longleftarrow ")
    | "\\longrightarrow"   -> LITERAL (TEX_ONLY  "\\longrightarrow ")
    | "\\Larr"             -> LITERAL (TEX_ONLY  "\\Leftarrow ")
    | "\\lArr"             -> LITERAL (TEX_ONLY  "\\Leftarrow ")
    | "\\Leftarrow"        -> LITERAL (TEX_ONLY  "\\Leftarrow ")
    | "\\Rarr"             -> LITERAL (TEX_ONLY  "\\Rightarrow ")
    | "\\rArr"             -> LITERAL (TEX_ONLY  "\\Rightarrow ")
    | "\\Rightarrow"       -> LITERAL (TEX_ONLY  "\\Rightarrow ")
    | "\\mapsto"           -> LITERAL (TEX_ONLY  "\\mapsto ")
    | "\\longmapsto"       -> LITERAL (TEX_ONLY  "\\longmapsto ")
    | "\\Longleftarrow"    -> LITERAL (TEX_ONLY  "\\Longleftarrow ")
    | "\\Longrightarrow"   -> LITERAL (TEX_ONLY  "\\Longrightarrow ")
    | "\\uarr"             -> DELIMITER (TEX_ONLY  "\\uparrow ")
    | "\\uparrow"          -> DELIMITER (TEX_ONLY  "\\uparrow ")
    | "\\uArr"             -> DELIMITER (TEX_ONLY  "\\Uparrow ")
    | "\\Uarr"             -> DELIMITER (TEX_ONLY  "\\Uparrow ")
    | "\\Uparrow"          -> DELIMITER (TEX_ONLY  "\\Uparrow ")
    | "\\darr"             -> DELIMITER (TEX_ONLY  "\\downarrow ")
    | "\\downarrow"        -> DELIMITER (TEX_ONLY  "\\downarrow ")
    | "\\dArr"             -> DELIMITER (TEX_ONLY  "\\Downarrow ")
    | "\\Darr"             -> DELIMITER (TEX_ONLY  "\\Downarrow ")
    | "\\Downarrow"        -> DELIMITER (TEX_ONLY  "\\Downarrow ")
    | "\\updownarrow"      -> DELIMITER (TEX_ONLY "\\updownarrow ")
    | "\\Updownarrow"      -> DELIMITER (TEX_ONLY "\\Updownarrow ")
    | "\\ulcorner"         -> DELIMITER (TEX_ONLY "\\ulcorner ")
    | "\\urcorner"         -> DELIMITER (TEX_ONLY "\\urcorner ")
    | "\\llcorner"         -> DELIMITER (TEX_ONLY "\\llcorner ")
    | "\\lrcorner"         -> DELIMITER (TEX_ONLY "\\lrcorner ")
    | "\\twoheadleftarrow" -> DELIMITER (TEX_ONLY "\\twoheadleftarrow ")
    | "\\twoheadrightarrow" -> DELIMITER (TEX_ONLY "\\twoheadrightarrow ")
    | "\\xleftarrow"       -> FUN_AR1 "\\xleftarrow "
    | "\\xrightarrow"       -> FUN_AR1 "\\xrightarrow "
    | "\\rightleftharpoons" -> DELIMITER (TEX_ONLY "\\rightleftharpoons ")
    | "\\leftrightarrow"   -> LITERAL (TEX_ONLY  "\\leftrightarrow ")
    | "\\lrarr"            -> LITERAL (TEX_ONLY  "\\leftrightarrow ")
    | "\\harr"             -> LITERAL (TEX_ONLY  "\\leftrightarrow ")
    | "\\Leftrightarrow"   -> LITERAL (TEX_ONLY  "\\Leftrightarrow ")
    | "\\Lrarr"            -> LITERAL (TEX_ONLY  "\\Leftrightarrow ")
    | "\\Harr"             -> LITERAL (TEX_ONLY  "\\Leftrightarrow ")
    | "\\lrArr"            -> LITERAL (TEX_ONLY  "\\Leftrightarrow ")
    | "\\hAar"             -> LITERAL (TEX_ONLY  "\\Leftrightarrow ")
    | "\\longleftrightarrow"-> LITERAL (TEX_ONLY  "\\longleftrightarrow ")
    | "\\Longleftrightarrow"-> LITERAL (TEX_ONLY  "\\Longleftrightarrow ")
    | "\\iff"              -> LITERAL (TEX_ONLY  "\\iff ")
    | "\\ll"		   -> LITERAL (TEX_ONLY "\\ll ")
    | "\\gg"		   -> LITERAL (TEX_ONLY "\\gg ")
    | "\\div"		   -> LITERAL (TEX_ONLY "\\div ")
    | "\\searrow"          -> LITERAL (TEX_ONLY "\\searrow ")
    | "\\nearrow"          -> LITERAL (TEX_ONLY "\\nearrow ")
    | "\\swarrow"          -> LITERAL (TEX_ONLY "\\swarrow ")
    | "\\nwarrow"          -> LITERAL (TEX_ONLY "\\nwarrow ")
    | "\\simeq"            -> LITERAL (TEX_ONLY "\\simeq ")
    | "\\ast"              -> LITERAL (TEX_ONLY "\\ast ")
    | "\\star"             -> LITERAL (TEX_ONLY "\\star ")
    | "\\ell"              -> LITERAL (TEX_ONLY "\\ell ")
    | "\\P"                -> LITERAL (TEX_ONLY "\\P ")
    | "\\smile"            -> LITERAL (TEX_ONLY "\\smile ")
    | "\\frown"            -> LITERAL (TEX_ONLY "\\frown ")
    | "\\bigcap"           -> LITERAL (TEX_ONLY "\\bigcap ")
    | "\\bigodot"          -> LITERAL (TEX_ONLY "\\bigodot ")
    | "\\bigcup"           -> LITERAL (TEX_ONLY "\\bigcup ")
    | "\\bigotimes"        -> LITERAL (TEX_ONLY "\\bigotimes ")
    | "\\coprod"           -> LITERAL (TEX_ONLY "\\coprod ")
    | "\\bigsqcup"         -> LITERAL (TEX_ONLY "\\bigsqcup ")
    | "\\bigoplus"         -> LITERAL (TEX_ONLY "\\bigoplus ")
    | "\\bigvee"           -> LITERAL (TEX_ONLY "\\bigvee ")
    | "\\biguplus"         -> LITERAL (TEX_ONLY "\\biguplus ")
    | "\\oint"             -> LITERAL (TEX_ONLY "\\oint ")
    | "\\bigwedge"         -> LITERAL (TEX_ONLY "\\bigwedge ")
    | "\\models"           -> LITERAL (TEX_ONLY "\\models ")
    | "\\vdash"            -> LITERAL (TEX_ONLY "\\vdash ")
    | "\\triangle"         -> LITERAL (TEX_ONLY "\\triangle ")
    | "\\bowtie"           -> LITERAL (TEX_ONLY "\\bowtie ")
    | "\\wr"               -> LITERAL (TEX_ONLY "\\wr ")
    | "\\triangleleft"     -> LITERAL (TEX_ONLY "\\triangleleft ")
    | "\\triangleright"    -> LITERAL (TEX_ONLY "\\triangleright ")
    | "\\textvisiblespace" -> LITERAL (TEX_ONLY "\\textvisiblespace ")
    | "\\circ"             -> LITERAL (TEX_ONLY "\\circ ")
    | "\\hbar"             -> LITERAL (TEX_ONLY "\\hbar ")
    | "\\imath"            -> LITERAL (TEX_ONLY "\\imath ")
    | "\\jmath"            -> LITERAL (TEX_ONLY "\\jmath ")
    | "\\lnot"             -> LITERAL (TEX_ONLY "\\lnot ")
    | "\\hookrightarrow"   -> LITERAL (TEX_ONLY "\\hookrightarrow ")
    | "\\hookleftarrow"    -> LITERAL (TEX_ONLY "\\hookleftarrow ")
    | "\\mp"               -> LITERAL (TEX_ONLY "\\mp ")
    | "\\approx"           -> LITERAL (TEX_ONLY  "\\approx ")
    | "\\propto"           -> LITERAL (TEX_ONLY "\\propto ")
    | "\\flat"             -> LITERAL (TEX_ONLY "\\flat ")
    | "\\sharp"            -> LITERAL (TEX_ONLY "\\sharp ")
    | "\\natural"          -> LITERAL (TEX_ONLY "\\natural ")
    | "\\int"              -> LITERAL (HTMLABLE_BIG ("\\int ", "&int;"))
    | "\\sum"              -> LITERAL (HTMLABLE_BIG ("\\sum ", "&sum;"))
    | "\\prod"             -> LITERAL (HTMLABLE_BIG ("\\prod ", "&prod;"))
    | "\\vdots"            -> LITERAL (TEX_ONLY "\\vdots ")
    | "\\limits"           -> LITERAL (TEX_ONLY "\\limits ")
    | "\\nolimits"         -> LITERAL (TEX_ONLY "\\nolimits ")
    | "\\top"              -> LITERAL (TEX_ONLY "\\top ")
    | "\\bullet"           -> LITERAL (TEX_ONLY "\\bullet ")
    | "\\bull"             -> LITERAL (TEX_ONLY "\\bullet ")
    | "\\angle"            -> LITERAL (TEX_ONLY "\\angle ")
    | "\\dagger"           -> LITERAL (TEX_ONLY "\\dagger ")
    | "\\ddagger"          -> LITERAL (TEX_ONLY "\\ddagger ")
    | "\\Dagger"           -> LITERAL (TEX_ONLY "\\ddagger ")
    | "\\colon"            -> LITERAL (TEX_ONLY "\\colon ")
    | "\\Vert"             -> DELIMITER (TEX_ONLY "\\Vert ")
    | "\\vert"             -> DELIMITER (TEX_ONLY "\\vert ")
    | "\\wp"               -> LITERAL (TEX_ONLY  "\\wp ")
    | "\\weierp"           -> LITERAL (TEX_ONLY  "\\wp ")
    | "\\wedge"            -> LITERAL (TEX_ONLY  "\\wedge ")
    | "\\and"              -> LITERAL (TEX_ONLY  "\\land ")
    | "\\land"             -> LITERAL (TEX_ONLY  "\\land ")
    | "\\vee"              -> LITERAL (TEX_ONLY  "\\vee ")
    | "\\or"               -> LITERAL (TEX_ONLY  "\\lor ")
    | "\\lor"              -> LITERAL (TEX_ONLY  "\\lor ")
    | "\\sub"              -> LITERAL (TEX_ONLY  "\\subset ")
    | "\\supe"             -> LITERAL (TEX_ONLY  "\\supseteq ")
    | "\\sube"             -> LITERAL (TEX_ONLY  "\\subseteq ")
    | "\\supset"           -> LITERAL (TEX_ONLY  "\\supset ")
    | "\\subset"           -> LITERAL (TEX_ONLY  "\\subset ")
    | "\\supseteq"         -> LITERAL (TEX_ONLY  "\\supseteq ")
    | "\\subseteq"         -> LITERAL (TEX_ONLY  "\\subseteq ")
    | "\\sqsupset"         -> LITERAL (TEX_ONLY "\\sqsupset ")
    | "\\sqsubset"         -> LITERAL (TEX_ONLY "\\sqsubset ")
    | "\\sqsupseteq"       -> LITERAL (TEX_ONLY "\\sqsupseteq ")
    | "\\sqsubseteq"       -> LITERAL (TEX_ONLY "\\sqsubseteq ")
    | "\\perp"             -> LITERAL (TEX_ONLY  "\\perp ")
    | "\\bot"              -> LITERAL (TEX_ONLY  "\\bot ")
    | "\\lfloor"           -> DELIMITER (TEX_ONLY  "\\lfloor ")
    | "\\rfloor"           -> DELIMITER (TEX_ONLY  "\\rfloor ")
    | "\\lceil"            -> DELIMITER (TEX_ONLY  "\\lceil ")
    | "\\rceil"            -> DELIMITER (TEX_ONLY  "\\rceil ")
    | "\\lbrace"           -> DELIMITER (TEX_ONLY "\\lbrace ")
    | "\\rbrace"           -> DELIMITER (TEX_ONLY "\\rbrace ")
    | "\\infty"            -> LITERAL (TEX_ONLY  "\\infty ")
    | "\\infin"            -> LITERAL (TEX_ONLY  "\\infty ")
    | "\\isin"             -> LITERAL (TEX_ONLY  "\\in ")
    | "\\in"               -> LITERAL (TEX_ONLY  "\\in ")
    | "\\ni"               -> LITERAL (TEX_ONLY  "\\ni ")
    | "\\notin"            -> LITERAL (TEX_ONLY  "\\notin ")
    | "\\smallsetminus"    -> LITERAL (TEX_ONLY "\\smallsetminus ")
    | "\\And"              -> LITERAL (TEX_ONLY "\\And ")
    | "\\forall"           -> LITERAL (TEX_ONLY "\\forall ")
    | "\\exists"           -> LITERAL (TEX_ONLY "\\exists ")
    | "\\exist"            -> LITERAL (TEX_ONLY "\\exists ")
    | "\\equiv"            -> LITERAL (TEX_ONLY "\\equiv ")
    | "\\ne"               -> LITERAL (TEX_ONLY "\\neq ")
    | "\\neq"              -> LITERAL (TEX_ONLY "\\neq ")
    | "\\Re"               -> LITERAL (TEX_ONLY  "\\Re ")
    | "\\real"             -> LITERAL (TEX_ONLY  "\\Re ")
    | "\\Im"               -> LITERAL (TEX_ONLY  "\\Im ")
    | "\\image"            -> LITERAL (TEX_ONLY  "\\Im ")
    | "\\prime"            -> LITERAL (TEX_ONLY "\\prime ")
    | "\\backslash"        -> DELIMITER (TEX_ONLY "\\backslash ")
    | "\\setminus"         -> LITERAL (TEX_ONLY "\\setminus ")
    | "\\times"            -> LITERAL (TEX_ONLY "\\times ")
    | "\\pm"               -> LITERAL (TEX_ONLY "\\pm ")
    | "\\plusmn"           -> LITERAL (TEX_ONLY "\\pm ")
    | "\\cdot"             -> LITERAL (TEX_ONLY "\\cdot ")
    | "\\AA"               -> LITERAL (TEX_ONLY "\\AA ")
    | "\\cdots"            -> LITERAL (TEX_ONLY "\\cdots ")
    | "\\sdot"             -> LITERAL (TEX_ONLY "\\cdot ")
    | "\\oplus"            -> LITERAL (TEX_ONLY "\\oplus ")
    | "\\otimes"           -> LITERAL (TEX_ONLY "\\otimes ")
    | "\\cap"              -> LITERAL (TEX_ONLY "\\cap ")
    | "\\cup"              -> LITERAL (TEX_ONLY "\\cup ")
    | "\\uplus"            -> LITERAL (TEX_ONLY "\\uplus ")
    | "\\sqcap"            -> LITERAL (TEX_ONLY "\\sqcap ")
    | "\\sqcup"            -> LITERAL (TEX_ONLY "\\sqcup ")
    | "\\empty"            -> LITERAL (TEX_ONLY "\\emptyset ")
    | "\\emptyset"         -> LITERAL (TEX_ONLY "\\emptyset ")
    | "\\O"                -> LITERAL (TEX_ONLY "\\emptyset ")
    | "\\S"                -> LITERAL (TEX_ONLY "\\S ")
    | "\\sect"             -> LITERAL (TEX_ONLY "\\S ")
    | "\\nabla"            -> LITERAL (TEX_ONLY "\\nabla ")
    | "\\geq"              -> LITERAL (TEX_ONLY "\\geq ")
    | "\\ge"               -> LITERAL (TEX_ONLY "\\geq ")
    | "\\leq"              -> LITERAL (TEX_ONLY "\\leq ")
    | "\\le"               -> LITERAL (TEX_ONLY "\\leq ")
    | "\\cong"             -> LITERAL (TEX_ONLY "\\cong ")
    | "\\ang"              -> LITERAL (TEX_ONLY "\\angle ")
    | "\\part"             -> LITERAL (TEX_ONLY "\\partial ")
    | "\\partial"          -> LITERAL (TEX_ONLY "\\partial ")
    | "\\ldots"            -> LITERAL (TEX_ONLY "\\ldots ")
    | "\\dots"             -> LITERAL (TEX_ONLY "\\dots ")
    | "\\quad"             -> LITERAL (TEX_ONLY "\\quad ")
    | "\\qquad"            -> LITERAL (TEX_ONLY "\\qquad ")
    | "\\mid"              -> LITERAL (TEX_ONLY "\\mid ")
    | "\\neg"              -> LITERAL (TEX_ONLY "\\neg ")
    | "\\langle"           -> DELIMITER (TEX_ONLY "\\langle ")
    | "\\rangle"           -> DELIMITER (TEX_ONLY "\\rangle ")
    | "\\lang"             -> DELIMITER (TEX_ONLY "\\langle ")
    | "\\rang"             -> DELIMITER (TEX_ONLY "\\rangle ")
    | "\\lbrack"           -> DELIMITER (TEX_ONLY "[")
    | "\\rbrack"           -> DELIMITER (TEX_ONLY "]")
    | "\\surd"             -> LITERAL (TEX_ONLY "\\surd ")
    | "\\ddots"            -> LITERAL (TEX_ONLY "\\ddots ")
    | "\\clubs"            -> LITERAL (TEX_ONLY "\\clubsuit ")
    | "\\clubsuit"         -> LITERAL (TEX_ONLY "\\clubsuit ")
    | "\\spades"           -> LITERAL (TEX_ONLY "\\spadesuit ")
    | "\\spadesuit"        -> LITERAL (TEX_ONLY "\\spadesuit ")
    | "\\hearts"           -> LITERAL (TEX_ONLY "\\heartsuit ")
    | "\\heartsuit"        -> LITERAL (TEX_ONLY "\\heartsuit ")
    | "\\diamonds"         -> LITERAL (TEX_ONLY "\\diamondsuit ")
    | "\\diamond"          -> LITERAL (TEX_ONLY "\\diamond ")
    | "\\bigtriangleup"    -> LITERAL (TEX_ONLY "\\bigtriangleup ")
    | "\\bigtriangledown"  -> LITERAL (TEX_ONLY "\\bigtriangledown ")
    | "\\diamondsuit"      -> LITERAL (TEX_ONLY "\\diamondsuit ")
    | "\\ominus"           -> LITERAL (TEX_ONLY "\\ominus ")
    | "\\oslash"           -> LITERAL (TEX_ONLY "\\oslash ")
    | "\\odot"             -> LITERAL (TEX_ONLY "\\odot ")
    | "\\bigcirc"          -> LITERAL (TEX_ONLY "\\bigcirc ")
    | "\\amalg"            -> LITERAL (TEX_ONLY "\\amalg ")
    | "\\prec"             -> LITERAL (TEX_ONLY "\\prec ")
    | "\\succ"             -> LITERAL (TEX_ONLY "\\succ ")
    | "\\preceq"           -> LITERAL (TEX_ONLY "\\preceq ")
    | "\\succeq"           -> LITERAL (TEX_ONLY "\\succeq ")
    | "\\dashv"            -> LITERAL (TEX_ONLY "\\dashv ")
    | "\\asymp"            -> LITERAL (TEX_ONLY "\\asymp ")
    | "\\doteq"            -> LITERAL (TEX_ONLY "\\doteq ")
    | "\\parallel"         -> LITERAL (TEX_ONLY "\\parallel ")
    | "\\euro"             -> LITERAL (TEX_ONLY "\\mbox{\\euro}")
    | "\\geneuro"          -> LITERAL (TEX_ONLY "\\mbox{\\geneuro}")
    | "\\geneuronarrow"    -> LITERAL (TEX_ONLY "\\mbox{\\geneuronarrow}")
    | "\\geneurowide"      -> LITERAL (TEX_ONLY "\\mbox{\\geneurowide}")
    | "\\officialeuro"     -> LITERAL (TEX_ONLY "\\mbox{\\officialeuro}")
    | "\\Coppa"            -> LITERAL (TEX_ONLY "\\mbox{\\Coppa}")
    | "\\coppa"            -> LITERAL (TEX_ONLY "\\mbox{\\coppa}")
    | "\\varcoppa"         -> LITERAL (TEX_ONLY "\\mbox{\\coppa}")
    | "\\Digamma"          -> LITERAL (TEX_ONLY "\\mbox{\\Digamma}")
    | "\\Koppa"            -> LITERAL (TEX_ONLY "\\mbox{\\Koppa}")
    | "\\koppa"            -> LITERAL (TEX_ONLY "\\mbox{\\koppa}")
    | "\\Sampi"            -> LITERAL (TEX_ONLY "\\mbox{\\Sampi}")
    | "\\sampi"            -> LITERAL (TEX_ONLY "\\mbox{\\sampi}")
    | "\\Stigma"           -> LITERAL (TEX_ONLY "\\mbox{\\Stigma}")
    | "\\stigma"           -> LITERAL (TEX_ONLY "\\mbox{\\stigma}")
    | "\\varstigma"        -> LITERAL (TEX_ONLY "\\mbox{\\varstigma}")
    | "\\implies"          -> LITERAL (TEX_ONLY "\\implies ")
    | "\\mod"              -> LITERAL (TEX_ONLY "\\mod ")
    | "\\Diamond"          -> LITERAL (TEX_ONLY "\\Diamond ")
    | "\\dotsb"            -> LITERAL (TEX_ONLY "\\dotsb ")
    | "\\dotsc"            -> LITERAL (TEX_ONLY "\\dotsc ")
    | "\\dotsi"            -> LITERAL (TEX_ONLY "\\dotsi ")
    | "\\dotsm"            -> LITERAL (TEX_ONLY "\\dotsm ")
    | "\\dotso"            -> LITERAL (TEX_ONLY "\\dotso ")
    | "\\reals"            -> LITERAL (TEX_ONLY "\\mathbb{R}")
    | "\\Reals"            -> LITERAL (TEX_ONLY "\\mathbb{R}")
    | "\\R"                -> LITERAL (TEX_ONLY "\\mathbb{R}")
    | "\\C"                -> LITERAL (TEX_ONLY "\\mathbb{C}")
    | "\\cnums"            -> LITERAL (TEX_ONLY "\\mathbb{C}")
    | "\\Complex"          -> LITERAL (TEX_ONLY "\\mathbb{C}")
    | "\\Z"                -> LITERAL (TEX_ONLY "\\mathbb{Z}")
    | "\\natnums"          -> LITERAL (TEX_ONLY "\\mathbb{N}")
    | "\\N"                -> LITERAL (TEX_ONLY "\\mathbb{N}")
    | "\\Q"                -> LITERAL (TEX_ONLY "\\mathbb{Q}")
    | "\\H"                -> LITERAL (TEX_ONLY "\\mathbb{H}")
    | "\\lVert"            -> LITERAL (TEX_ONLY "\\lVert ")
    | "\\rVert"            -> LITERAL (TEX_ONLY "\\rVert ")
    | "\\nmid"             -> LITERAL (TEX_ONLY "\\nmid ")
    | "\\lesssim"          -> LITERAL (TEX_ONLY "\\lesssim ")
    | "\\ngeq"             -> LITERAL (TEX_ONLY "\\ngeq ")
    | "\\smallsmile"       -> LITERAL (TEX_ONLY "\\smallsmile ")
    | "\\smallfrown"       -> LITERAL (TEX_ONLY "\\smallfrown ")
    | "\\nleftarrow"       -> LITERAL (TEX_ONLY "\\nleftarrow ")
    | "\\nrightarrow"      -> LITERAL (TEX_ONLY "\\nrightarrow ")
    | "\\trianglelefteq"   -> LITERAL (TEX_ONLY "\\trianglelefteq ")
    | "\\trianglerighteq"  -> LITERAL (TEX_ONLY "\\trianglerighteq ")
    | "\\square"           -> LITERAL (TEX_ONLY "\\square ")
    | "\\checkmark"        -> LITERAL (TEX_ONLY "\\checkmark ")
    | "\\supsetneq"        -> LITERAL (TEX_ONLY "\\supsetneq ")
    | "\\subsetneq"        -> LITERAL (TEX_ONLY "\\subsetneq ")
    | "\\Box"              -> LITERAL (TEX_ONLY "\\Box ")
    | "\\nleq"             -> LITERAL (TEX_ONLY "\\nleq ")
    | "\\upharpoonright"   -> LITERAL (TEX_ONLY "\\upharpoonright ")
    | "\\restriction"      -> LITERAL (TEX_ONLY "\\upharpoonright ")
    | "\\upharpoonleft"    -> LITERAL (TEX_ONLY "\\upharpoonleft ")
    | "\\downharpoonright" -> LITERAL (TEX_ONLY "\\downharpoonright ")
    | "\\downharpoonleft"  -> LITERAL (TEX_ONLY "\\downharpoonleft ")
    | "\\rightharpoonup"   -> LITERAL (TEX_ONLY "\\rightharpoonup ")
    | "\\rightharpoondown" -> LITERAL (TEX_ONLY "\\rightharpoondown ")
    | "\\leftharpoonup"    -> LITERAL (TEX_ONLY "\\leftharpoonup ")
    | "\\leftharpoondown"  -> LITERAL (TEX_ONLY "\\leftharpoondown ")
    | "\\nless"            -> LITERAL (TEX_ONLY "\\nless ")
    | "\\Vdash"            -> LITERAL (TEX_ONLY "\\Vdash ")
    | "\\vDash"            -> LITERAL (TEX_ONLY "\\vDash ")
    | "\\varkappa"         -> LITERAL (TEX_ONLY "\\varkappa ")
    | "\\digamma"          -> LITERAL (TEX_ONLY "\\digamma ")
    | "\\beth"             -> LITERAL (TEX_ONLY "\\beth ")
    | "\\daleth"           -> LITERAL (TEX_ONLY "\\daleth ")
    | "\\gimel"            -> LITERAL (TEX_ONLY "\\gimel ")
    | "\\complement"       -> LITERAL (TEX_ONLY "\\complement ")
    | "\\eth"              -> LITERAL (TEX_ONLY "\\eth ")
    | "\\hslash"           -> LITERAL (TEX_ONLY "\\hslash ")
    | "\\mho"              -> LITERAL (TEX_ONLY "\\mho ")
    | "\\Finv"             -> LITERAL (TEX_ONLY "\\Finv ")
    | "\\Game"             -> LITERAL (TEX_ONLY "\\Game ")
    | "\\varlimsup"        -> LITERAL (TEX_ONLY "\\varlimsup ")
    | "\\varliminf"        -> LITERAL (TEX_ONLY "\\varliminf ")
    | "\\varinjlim"        -> LITERAL (TEX_ONLY "\\varinjlim ")
    | "\\varprojlim"       -> LITERAL (TEX_ONLY "\\varprojlim ")
    | "\\injlim"           -> LITERAL (TEX_ONLY "\\injlim ")
    | "\\projlim"          -> LITERAL (TEX_ONLY "\\projlim ")
    | "\\iint"             -> LITERAL (TEX_ONLY "\\iint ")
    | "\\iiint"            -> LITERAL (TEX_ONLY "\\iiint ")
    | "\\iiiint"           -> LITERAL (TEX_ONLY "\\iiiint ")
    | "\\varnothing"       -> LITERAL (TEX_ONLY "\\varnothing ")
    | "\\left"             -> LEFT
    | "\\right"            -> RIGHT
    | "\\hat"              -> FUN_AR1 "\\hat "
    | "\\hline"            -> LITERAL (TEX_ONLY "\\hline ")
    | "\\vline"            -> LITERAL (TEX_ONLY "\\vline ")
    | "\\widetilde"        -> LITERAL (TEX_ONLY "\\widetilde ")
    | "\\widehat"          -> LITERAL (TEX_ONLY "\\widehat ")
    | "\\overline"         -> LITERAL (TEX_ONLY "\\overline ")
    | "\\overbrace"        -> LITERAL (TEX_ONLY "\\overbrace ")
    | "\\underline"        -> LITERAL (TEX_ONLY "\\underline ")
    | "\\underbrace"       -> LITERAL (TEX_ONLY "\\underbrace ")
    | "\\overleftarrow"    -> LITERAL (TEX_ONLY "\\overleftarrow ")
    | "\\overrightarrow"   -> LITERAL (TEX_ONLY "\\overrightarrow ")
    | "\\overleftrightarrow"-> LITERAL (TEX_ONLY "\\overleftrightarrow ")
    | "\\check"            -> FUN_AR1 "\\check "
    | "\\acute"            -> FUN_AR1 "\\acute "
    | "\\grave"            -> FUN_AR1 "\\grave "
    | "\\bar"              -> FUN_AR1 "\\bar "
    | "\\vec"              -> FUN_AR1 "\\vec "
    | "\\dot"              -> FUN_AR1 "\\dot "
    | "\\ddot"             -> FUN_AR1 "\\ddot "
    | "\\breve"            -> FUN_AR1 "\\breve "
    | "\\tilde"            -> FUN_AR1 "\\tilde "
    | "\\not"              -> LITERAL (TEX_ONLY "\\not ")
    | "\\choose"           -> FUN_INFIX "\\choose "
    | "\\atop"             -> FUN_INFIX "\\atop "
    | "\\binom"            -> FUN_AR2 "\\binom "
    | "\\dbinom"            -> FUN_AR2 "\\dbinom "
    | "\\tbinom"            -> FUN_AR2 "\\tbinom "
    | "\\stackrel"         -> FUN_AR2 "\\stackrel "
    | "\\sideset"         -> FUN_AR2nb "\\sideset "
    | "\\underset"         -> FUN_AR2 "\\underset "
    | "\\overset"         -> FUN_AR2 "\\overset "
    | "\\frac"             -> FUN_AR2 "\\frac "
    | "\\dfrac"             -> FUN_AR2 "\\dfrac "
    | "\\tfrac"             -> FUN_AR2 "\\tfrac "
    | "\\cfrac"            -> FUN_AR2 "\\cfrac " 
    | "\\over"             -> FUN_INFIX "\\over "
    | "\\sqrt"             -> FUN_AR1 "\\sqrt "
    | "\\cancel"           -> FUN_AR1 "\\cancel "
    | "\\bcancel"           -> FUN_AR1 "\\bcancel "
    | "\\xcancel"           -> FUN_AR1 "\\xcancel "
    | "\\cancelto"         -> FUN_AR2 "\\cancelto "
    | "\\pmod"             -> FUN_AR1hl ("\\pmod ", ("(mod ", ")"))
    | "\\bmod"             -> FUN_AR1hl ("\\bmod ", ("mod ", ""))
    | "\\emph"             -> FUN_AR1 "\\emph "
    | "\\texttt"           -> FUN_AR1 "\\texttt "
    | "\\textbf"           -> FUN_AR1 "\\textbf "
    | "\\textsf"           -> FUN_AR1 "\\textsf "
    | "\\textit"           -> FUN_AR1hf ("\\textit ", FONTFORCE_IT)
    | "\\textrm"           -> FUN_AR1hf ("\\textrm ", FONTFORCE_RM)
    | "\\rm"               -> DECLh ("\\rm ", FONTFORCE_RM)
    | "\\it"               -> DECLh ("\\it ", FONTFORCE_IT)
    | "\\cal"              -> DECL "\\cal "
    | "\\displaystyle"     -> LITERAL (TEX_ONLY  "\\displaystyle ")
    | "\\scriptstyle"      -> LITERAL (TEX_ONLY "\\scriptstyle ")
    | "\\textstyle"        -> LITERAL (TEX_ONLY "\\textstyle ")
    | "\\scriptscriptstyle"-> LITERAL (TEX_ONLY "\\scriptscriptstyle ")
    | "\\bf"               -> DECL "\\bf "
    | "\\big"              -> BIG "\\big "
    | "\\Big"              -> BIG "\\Big "
    | "\\bigg"             -> BIG "\\bigg "
    | "\\Bigg"             -> BIG "\\Bigg "
    | "\\bigl"             -> BIG "\\bigl "
    | "\\bigr"             -> BIG "\\bigr "
    | "\\Bigl"             -> BIG "\\Bigl "
    | "\\Bigr"             -> BIG "\\Bigr "
    | "\\biggl"             -> BIG "\\biggl "
    | "\\biggr"             -> BIG "\\biggr "
    | "\\Biggl"             -> BIG "\\Biggl "
    | "\\Biggr"             -> BIG "\\Biggr "
    | "\\vartriangle"      -> LITERAL (TEX_ONLY "\\vartriangle ")
    | "\\triangledown"     -> LITERAL (TEX_ONLY "\\triangledown ")
    | "\\lozenge"          -> LITERAL (TEX_ONLY "\\lozenge ")
    | "\\circledS"         -> LITERAL (TEX_ONLY "\\circledS ")
    | "\\measuredangle"    -> LITERAL (TEX_ONLY "\\measuredangle ")
    | "\\nexists"          -> LITERAL (TEX_ONLY "\\nexists ")
    | "\\Bbbk"             -> LITERAL (TEX_ONLY "\\Bbbk ")
    | "\\backprime"        -> LITERAL (TEX_ONLY "\\backprime ")
    | "\\blacktriangle"    -> LITERAL (TEX_ONLY "\\blacktriangle ")
    | "\\blacktriangledown"-> LITERAL (TEX_ONLY "\\blacktriangledown ")
    | "\\blacksquare"      -> LITERAL (TEX_ONLY "\\blacksquare ")
    | "\\blacklozenge"     -> LITERAL (TEX_ONLY "\\blacklozenge ")
    | "\\bigstar"          -> LITERAL (TEX_ONLY "\\bigstar ")
    | "\\sphericalangle"   -> LITERAL (TEX_ONLY "\\sphericalangle ")
    | "\\diagup"           -> LITERAL (TEX_ONLY "\\diagup ")
    | "\\diagdown"         -> LITERAL (TEX_ONLY "\\diagdown ")
    | "\\dotplus"          -> LITERAL (TEX_ONLY "\\dotplus ")
    | "\\Cap"              -> LITERAL (TEX_ONLY "\\Cap ")
    | "\\doublecap"        -> LITERAL (TEX_ONLY "\\Cap ")
    | "\\Cup"              -> LITERAL (TEX_ONLY "\\Cup ")
    | "\\doublecup"        -> LITERAL (TEX_ONLY "\\Cup ")
    | "\\barwedge"         -> LITERAL (TEX_ONLY "\\barwedge ")
    | "\\veebar"           -> LITERAL (TEX_ONLY "\\veebar ")
    | "\\doublebarwedge"   -> LITERAL (TEX_ONLY "\\doublebarwedge ")
    | "\\boxminus"         -> LITERAL (TEX_ONLY "\\boxminus ")
    | "\\boxtimes"         -> LITERAL (TEX_ONLY "\\boxtimes ")
    | "\\boxdot"           -> LITERAL (TEX_ONLY "\\boxdot ")
    | "\\boxplus"          -> LITERAL (TEX_ONLY "\\boxplus ")
    | "\\divideontimes"    -> LITERAL (TEX_ONLY "\\divideontimes ")
    | "\\ltimes"           -> LITERAL (TEX_ONLY "\\ltimes ")
    | "\\rtimes"           -> LITERAL (TEX_ONLY "\\rtimes ")
    | "\\leftthreetimes"   -> LITERAL (TEX_ONLY "\\leftthreetimes ")
    | "\\rightthreetimes"  -> LITERAL (TEX_ONLY "\\rightthreetimes ")
    | "\\curlywedge"       -> LITERAL (TEX_ONLY "\\curlywedge ")
    | "\\curlyvee"         -> LITERAL (TEX_ONLY "\\curlyvee ")
    | "\\circleddash"      -> LITERAL (TEX_ONLY "\\circleddash ")
    | "\\circledast"       -> LITERAL (TEX_ONLY "\\circledast ")
    | "\\circledcirc"      -> LITERAL (TEX_ONLY "\\circledcirc ")
    | "\\centerdot"        -> LITERAL (TEX_ONLY "\\centerdot ")
    | "\\intercal"         -> LITERAL (TEX_ONLY "\\intercal ")
    | "\\leqq"             -> LITERAL (TEX_ONLY "\\leqq ")
    | "\\leqslant"         -> LITERAL (TEX_ONLY "\\leqslant ")
    | "\\eqslantless"      -> LITERAL (TEX_ONLY "\\eqslantless ")
    | "\\lessapprox"       -> LITERAL (TEX_ONLY "\\lessapprox ")
    | "\\approxeq"         -> LITERAL (TEX_ONLY "\\approxeq ")
    | "\\lessdot"          -> LITERAL (TEX_ONLY "\\lessdot ")
    | "\\lll"              -> LITERAL (TEX_ONLY "\\lll ")
    | "\\lessgtr"          -> LITERAL (TEX_ONLY "\\lessgtr ")
    | "\\lesseqgtr"        -> LITERAL (TEX_ONLY "\\lesseqgtr ")
    | "\\lesseqqgtr"       -> LITERAL (TEX_ONLY "\\lesseqqgtr ")
    | "\\doteqdot"         -> LITERAL (TEX_ONLY "\\doteqdot ")
    | "\\Doteq"            -> LITERAL (TEX_ONLY "\\doteqdot ")
    | "\\risingdotseq"     -> LITERAL (TEX_ONLY "\\risingdotseq ")
    | "\\fallingdotseq"    -> LITERAL (TEX_ONLY "\\fallingdotseq ")
    | "\\backsim"          -> LITERAL (TEX_ONLY "\\backsim ")
    | "\\backsimeq"        -> LITERAL (TEX_ONLY "\\backsimeq ")
    | "\\subseteqq"        -> LITERAL (TEX_ONLY "\\subseteqq ")
    | "\\Subset"           -> LITERAL (TEX_ONLY "\\Subset ")
    | "\\preccurlyeq"      -> LITERAL (TEX_ONLY "\\preccurlyeq ")
    | "\\curlyeqprec"      -> LITERAL (TEX_ONLY "\\curlyeqprec ")
    | "\\precsim"          -> LITERAL (TEX_ONLY "\\precsim ")
    | "\\precapprox"       -> LITERAL (TEX_ONLY "\\precapprox ")
    | "\\vartriangleleft"  -> LITERAL (TEX_ONLY "\\vartriangleleft ")
    | "\\Vvdash"           -> LITERAL (TEX_ONLY "\\Vvdash ")
    | "\\bumpeq"           -> LITERAL (TEX_ONLY "\\bumpeq ")
    | "\\Bumpeq"           -> LITERAL (TEX_ONLY "\\Bumpeq ")
    | "\\geqq"             -> LITERAL (TEX_ONLY "\\geqq ")
    | "\\geqslant"         -> LITERAL (TEX_ONLY "\\geqslant ")
    | "\\eqslantgtr"       -> LITERAL (TEX_ONLY "\\eqslantgtr ")
    | "\\gtrsim"           -> LITERAL (TEX_ONLY "\\gtrsim ")
    | "\\gtrapprox"        -> LITERAL (TEX_ONLY "\\gtrapprox ")
    | "\\eqsim"            -> LITERAL (TEX_ONLY "\\eqsim ")
    | "\\gtrdot"           -> LITERAL (TEX_ONLY "\\gtrdot ")
    | "\\ggg"              -> LITERAL (TEX_ONLY "\\ggg ")
    | "\\gggtr"            -> LITERAL (TEX_ONLY "\\ggg ")
    | "\\gtrless"          -> LITERAL (TEX_ONLY "\\gtrless ")
    | "\\gtreqless"        -> LITERAL (TEX_ONLY "\\gtreqless ")
    | "\\gtreqqless"       -> LITERAL (TEX_ONLY "\\gtreqqless ")
    | "\\eqcirc"           -> LITERAL (TEX_ONLY "\\eqcirc ")
    | "\\circeq"           -> LITERAL (TEX_ONLY "\\circeq ")
    | "\\triangleq"        -> LITERAL (TEX_ONLY "\\triangleq ")
    | "\\thicksim"         -> LITERAL (TEX_ONLY "\\thicksim ")
    | "\\thickapprox"      -> LITERAL (TEX_ONLY "\\thickapprox ")
    | "\\supseteqq"        -> LITERAL (TEX_ONLY "\\supseteqq ")
    | "\\Supset"           -> LITERAL (TEX_ONLY "\\Supset ")
    | "\\succcurlyeq"      -> LITERAL (TEX_ONLY "\\succcurlyeq ")
    | "\\curlyeqsucc"      -> LITERAL (TEX_ONLY "\\curlyeqsucc ")
    | "\\succsim"          -> LITERAL (TEX_ONLY "\\succsim ")
    | "\\succapprox"       -> LITERAL (TEX_ONLY "\\succapprox ")
    | "\\vartriangleright" -> LITERAL (TEX_ONLY "\\vartriangleright ")
    | "\\shortmid"         -> LITERAL (TEX_ONLY "\\shortmid ")
    | "\\shortparallel"    -> LITERAL (TEX_ONLY "\\shortparallel ")
    | "\\between"          -> LITERAL (TEX_ONLY "\\between ")
    | "\\pitchfork"        -> LITERAL (TEX_ONLY "\\pitchfork ")
    | "\\varpropto"        -> LITERAL (TEX_ONLY "\\varpropto ")
    | "\\blacktriangleleft"-> LITERAL (TEX_ONLY "\\blacktriangleleft ")
    | "\\therefore"        -> LITERAL (TEX_ONLY "\\therefore ")
    | "\\backepsilon"      -> LITERAL (TEX_ONLY "\\backepsilon ")
    | "\\blacktriangleright"-> LITERAL (TEX_ONLY "\\blacktriangleright ")
    | "\\because"          -> LITERAL (TEX_ONLY "\\because ")
    | "\\nleqslant"        -> LITERAL (TEX_ONLY "\\nleqslant ")
    | "\\nleqq"            -> LITERAL (TEX_ONLY "\\nleqq ")
    | "\\lneq"             -> LITERAL (TEX_ONLY "\\lneq ")
    | "\\lneqq"            -> LITERAL (TEX_ONLY "\\lneqq ")
    | "\\lvertneqq"        -> LITERAL (TEX_ONLY "\\lvertneqq ")
    | "\\lnsim"            -> LITERAL (TEX_ONLY "\\lnsim ")
    | "\\lnapprox"         -> LITERAL (TEX_ONLY "\\lnapprox ")
    | "\\nprec"            -> LITERAL (TEX_ONLY "\\nprec ")
    | "\\npreceq"          -> LITERAL (TEX_ONLY "\\npreceq ")
    | "\\precneqq"         -> LITERAL (TEX_ONLY "\\precneqq ")
    | "\\precnsim"         -> LITERAL (TEX_ONLY "\\precnsim ")
    | "\\precnapprox"      -> LITERAL (TEX_ONLY "\\precnapprox ")
    | "\\nsim"             -> LITERAL (TEX_ONLY "\\nsim ")
    | "\\nshortmid"        -> LITERAL (TEX_ONLY "\\nshortmid ")
    | "\\nvdash"           -> LITERAL (TEX_ONLY "\\nvdash ")
    | "\\nVdash"           -> LITERAL (TEX_ONLY "\\nVdash ")
    | "\\ntriangleleft"    -> LITERAL (TEX_ONLY "\\ntriangleleft ")
    | "\\ntrianglelefteq"  -> LITERAL (TEX_ONLY "\\ntrianglelefteq ")
    | "\\nsubseteq"        -> LITERAL (TEX_ONLY "\\nsubseteq ")
    | "\\nsubseteqq"       -> LITERAL (TEX_ONLY "\\nsubseteqq ")
    | "\\varsubsetneq"     -> LITERAL (TEX_ONLY "\\varsubsetneq ")
    | "\\subsetneqq"       -> LITERAL (TEX_ONLY "\\subsetneqq ")
    | "\\varsubsetneqq"    -> LITERAL (TEX_ONLY "\\varsubsetneqq ")
    | "\\ngtr"             -> LITERAL (TEX_ONLY "\\ngtr ")
    | "\\ngeqslant"        -> LITERAL (TEX_ONLY "\\ngeqslant ")
    | "\\ngeqq"            -> LITERAL (TEX_ONLY "\\ngeqq ")
    | "\\gneq"             -> LITERAL (TEX_ONLY "\\gneq ")
    | "\\gneqq"            -> LITERAL (TEX_ONLY "\\gneqq ")
    | "\\gvertneqq"        -> LITERAL (TEX_ONLY "\\gvertneqq ")
    | "\\gnsim"            -> LITERAL (TEX_ONLY "\\gnsim ")
    | "\\gnapprox"         -> LITERAL (TEX_ONLY "\\gnapprox ")
    | "\\nsucc"            -> LITERAL (TEX_ONLY "\\nsucc ")
    | "\\nsucceq"          -> LITERAL (TEX_ONLY "\\nsucceq ")
    | "\\succneqq"         -> LITERAL (TEX_ONLY "\\succneqq ")
    | "\\succnsim"         -> LITERAL (TEX_ONLY "\\succnsim ")
    | "\\succnapprox"      -> LITERAL (TEX_ONLY "\\succnapprox ")
    | "\\ncong"            -> LITERAL (TEX_ONLY "\\ncong ")
    | "\\nshortparallel"   -> LITERAL (TEX_ONLY "\\nshortparallel ")
    | "\\nparallel"        -> LITERAL (TEX_ONLY "\\nparallel ")
    | "\\nvDash"           -> LITERAL (TEX_ONLY "\\nvDash ")
    | "\\nVDash"           -> LITERAL (TEX_ONLY "\\nVDash ")
    | "\\ntriangleright"   -> LITERAL (TEX_ONLY "\\ntriangleright ")
    | "\\ntrianglerighteq" -> LITERAL (TEX_ONLY "\\ntrianglerighteq ")
    | "\\nsupseteq"        -> LITERAL (TEX_ONLY "\\nsupseteq ")
    | "\\nsupseteqq"       -> LITERAL (TEX_ONLY "\\nsupseteqq ")
    | "\\varsupsetneq"     -> LITERAL (TEX_ONLY "\\varsupsetneq ")
    | "\\supsetneqq"       -> LITERAL (TEX_ONLY "\\supsetneqq ")
    | "\\varsupsetneqq"    -> LITERAL (TEX_ONLY "\\varsupsetneqq ")
    | "\\leftleftarrows"   -> LITERAL (TEX_ONLY "\\leftleftarrows ")
    | "\\leftrightarrows"  -> LITERAL (TEX_ONLY "\\leftrightarrows ")
    | "\\Lleftarrow"       -> LITERAL (TEX_ONLY "\\Lleftarrow ")
    | "\\leftarrowtail"    -> LITERAL (TEX_ONLY "\\leftarrowtail ")
    | "\\looparrowleft"    -> LITERAL (TEX_ONLY "\\looparrowleft ")
    | "\\leftrightharpoons"-> LITERAL (TEX_ONLY "\\leftrightharpoons ")
    | "\\curvearrowleft"   -> LITERAL (TEX_ONLY "\\curvearrowleft ")
    | "\\circlearrowleft"  -> LITERAL (TEX_ONLY "\\circlearrowleft ")
    | "\\Lsh"              -> LITERAL (TEX_ONLY "\\Lsh ")
    | "\\upuparrows"       -> LITERAL (TEX_ONLY "\\upuparrows ")
    | "\\rightrightarrows" -> LITERAL (TEX_ONLY "\\rightrightarrows ")
    | "\\rightleftarrows"  -> LITERAL (TEX_ONLY "\\rightleftarrows ")
    | "\\Rrightarrow"      -> LITERAL (TEX_ONLY "\\Rrightarrow ")
    | "\\rightarrowtail"   -> LITERAL (TEX_ONLY "\\rightarrowtail ")
    | "\\looparrowright"   -> LITERAL (TEX_ONLY "\\looparrowright ")
    | "\\curvearrowright"  -> LITERAL (TEX_ONLY "\\curvearrowright ")
    | "\\circlearrowright" -> LITERAL (TEX_ONLY "\\circlearrowright ")
    | "\\Rsh"              -> LITERAL (TEX_ONLY "\\Rsh ")
    | "\\downdownarrows"   -> LITERAL (TEX_ONLY "\\downdownarrows ")
    | "\\multimap"         -> LITERAL (TEX_ONLY "\\multimap ")
    | "\\leftrightsquigarrow"-> LITERAL (TEX_ONLY "\\leftrightsquigarrow ")
    | "\\rightsquigarrow"  -> LITERAL (TEX_ONLY "\\rightsquigarrow ")
    | "\\nLeftarrow"       -> LITERAL (TEX_ONLY "\\nLeftarrow ")
    | "\\nleftrightarrow"  -> LITERAL (TEX_ONLY "\\nleftrightarrow ")
    | "\\nRightarrow"      -> LITERAL (TEX_ONLY "\\nRightarrow ")
    | "\\nLeftrightarrow"  -> LITERAL (TEX_ONLY "\\nLeftrightarrow ")
    | "\\mathit"           -> FUN_AR1hf ("\\mathit ", FONTFORCE_IT)
    | "\\mathrm"           -> FUN_AR1hf ("\\mathrm ", FONTFORCE_RM)
    | "\\mathord"          -> FUN_AR1 "\\mathord "
    | "\\mathop"           -> FUN_AR1 "\\mathop "
    | "\\mathbin"          -> FUN_AR1 "\\mathbin "
    | "\\mathrel"          -> FUN_AR1 "\\mathrel "
    | "\\mathopen"         -> FUN_AR1 "\\mathopen "
    | "\\mathclose"        -> FUN_AR1 "\\mathclose "
    | "\\mathpunct"        -> FUN_AR1 "\\mathpunct "
    | "\\boldsymbol"       -> FUN_AR1 "\\boldsymbol "
    | "\\bold"             -> FUN_AR1 "\\mathbf "
    | "\\Bbb"              -> FUN_AR1 "\\mathbb "
    | "\\mathbf"           -> FUN_AR1 "\\mathbf "
    | "\\mathsf"           -> FUN_AR1 "\\mathsf "
    | "\\mathcal"          -> FUN_AR1 "\\mathcal "
    | "\\mathbb"           -> FUN_AR1 "\\mathbb "
    | "\\mathtt"           -> FUN_AR1 "\\mathtt "
    | "\\mathfrak"         -> FUN_AR1 "\\mathfrak "
    | "\\operatorname"     -> FUN_AR1 "\\operatorname "
    | "\\text"             -> raise (Failure "malformatted \\text")
    | "\\mbox"             -> raise (Failure "malformatted \\mbox")
    | "\\vbox"             -> raise (Failure "malformatted \\vbox")
    | "\\hbox"             -> raise (Failure "malformatted \\hbox")
    | "\\color"            -> LITERAL (TEX_ONLY "\\color")
    | "\\pagecolor"        -> LITERAL (TEX_ONLY "\\pagecolor")
    | "\\definecolor"      -> LITERAL (TEX_ONLY "\\definecolor")
    | s                    -> raise (Illegal_tex_function s)
