<?php

/**
 * API extension to fetch data from mathematical Wikidata items
 */
class ApiMathWikidataExtracts extends ApiQueryBase {
	/**
	 * @var string the prefix of the parameter names of this API
	 */
	const PREFIX = "math";

	/**
	 * @var MathWikidataConnector
	 */
	private $wikidata;

	/**
	 * @param ApiQuery $query
	 * @param string $moduleName
	 */
	public function __construct( ApiQuery $query, $moduleName ) {
		parent::__construct( $query, $moduleName, self::PREFIX );
		$this->wikidata = MathWikidataConnector::getInstance();
	}

	/**
	 * @throws ApiUsageException
	 */
	public function execute() {
		$result = $this->getResult();
		$params = $this->extractRequestParams();

		$qid = $params['qid'];
		$lang = $params['uselang'] ?: 'en';

		try {
			$info = $this->wikidata->fetchWikidataFromId( $qid, $lang );
			$result->addValue(
				[ 'query', 'wikidataextracts' ],
				$qid,
				$this->buildResponse( $qid, $lang, $info )
			);
		} catch ( MWException $e ) {
			// impossible to fetch the data. Keep the answer empty
			$result->addValue(
				[ 'query', 'wikidataextracts' ],
				$qid,
				[]
			);
		}
	}

	/**
	 * @param string $qid
	 * @param string $lang language code
	 * @param MathWikidataInfo $info information from MathWikidataConnector
	 * @return array response
	 */
	private function buildResponse( $qid, $lang, $info ) {
		$specialPageTitle = Title::newFromText( "Special:MathWikidata" );
		$url = $specialPageTitle->getLocalURL( [
			'qid' => $qid
		] );

		try {
			$langObj = Language::factory( $lang );
		} catch ( MWException $e ) {
			throw new InvalidArgumentException( "Invalid language code." );
		}

		return [
			"title" => $info->getLabel(),
			"extract"  => self::buildHTMLRepresentation( $info ),
			"canonicalurl" => $url,
			"fullurl" => $url,
			"contentmodel" => "wikitext",
			"pagelanguage" => $lang,
			"pagelanguagedir" => $langObj->getDir(),
			"pagelanguagehtmlcode" => "wikidataextracts"
		];
	}

	/**
	 * Generates an HTML string from the given data.
	 * @param MathWikidataInfo $info an info object generated by fetchWikidataFromId
	 * @return string an HTML representation of the given info object
	 */
	private function buildHTMLRepresentation( $info ) {
		$output = Html::openElement( "div" );
		$output .= Html::openElement( "b" );
		$output .= $info->getLabel();
		$output .= Html::closeElement( "b" );

		$output .= " (" . $info->getDescription() . ")";
		$output .= Html::closeElement( "div" );

		$output .= $info->generateHTMLOfParts();

		return $output;
	}

	/**
	 * Defines the parameters for this API endpoint
	 * @return array
	 */
	public function getAllowedParams() {
		return [
			'qid' => [
				ApiBase::PARAM_TYPE => 'string',
				ApiBase::PARAM_REQUIRED => true
			],
			'uselang' => [
				ApiBase::PARAM_TYPE => 'string',
				ApiBase::PARAM_REQUIRED => false
			]
		];
	}

	/**
	 * @see ApiBase::getExamplesMessages()
	 * @return array
	 */
	protected function getExamplesMessages() {
		return [
			'action=query&prop=wikidataextracts&mathqid=Q35875&mathuselang=en'
			=> 'apihelp-query+wikidataextracts-example-1',
		];
	}

	/**
	 * @see ApiBase::getHelpUrls()
	 * @return string
	 */
	public function getHelpUrls() {
		return 'https://www.mediawiki.org/wiki/Extension:Math#API';
	}
}
